name: Autotag

on:
  push:
    branches:
      - main
      - master

jobs:
  autotag:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Identify version
      id: read_version
      run: |
        cd ./src
        echo "Identifying version..."
        VERSION=$(jq -r '.version' manifest.json)
        echo "version=$VERSION" >> $GITHUB_ENV  # Set version as an environment variable

    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse "refs/tags/${{ env.version }}" >/dev/null 2>&1; then
          echo "Tag ${{ env.version }} already exists."
          echo "tag_exists=true" >> $GITHUB_ENV  # Set tag_exists to true in the environment
        else
          echo "Tag ${{ env.version }} does not exist."
          echo "tag_exists=false" >> $GITHUB_ENV  # Set tag_exists to false in the environment
        fi

    - name: Create and push tag using GITHUB_TOKEN
      if: env.tag_exists == 'false'
      id: create_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating tag ${{ env.version }}..."
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/git/tags \
          -d @- <<EOF
        {
          "tag": "${{ env.version }}",
          "message": "Release version ${{ env.version }}",
          "object": "$(git rev-parse HEAD)",
          "type": "commit",
          "tagger": {
            "name": "${{ github.actor }}",
            "email": "${{ github.actor }}@users.noreply.github.com",
            "date": "$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
          }
        }
        EOF

        echo "Pushing tag to remote..."
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/git/refs \
          -d @- <<EOF
        {
          "ref": "refs/tags/${{ env.version }}",
          "sha": "$(git rev-parse HEAD)"
        }
        EOF

        echo "tag_name=${{ env.version }}" >> $GITHUB_ENV  # Set the tag_name for later use in the workflow

    - name: Output tag name
      run: |
        echo "Tag created: ${{ env.version }}"