name: Autotag

on:
  push:
    branches:
      - main
      - master

jobs:
  autotag:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Identify version
      id: read_version
      run: |
        cd ./src
        echo identifying version...
        VERSION=$(jq -r '.version' manifest.json)
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Version: $VERSION"
        cd ../

    - name: Check if tag exists
      id: check_tag
      run: |
        VERSION=${{ steps.read_version.outputs.version }}
        if git rev-parse "$VERSION" >/dev/null 2>&1; then
          echo "Tag $VERSION already exists."
          echo "tag_exists=true" >> $GITHUB_ENV
        else
          echo "Tag $VERSION does not exist."
          echo "tag_exists=false" >> $GITHUB_ENV
        fi

    - name: test
      run: |
        echo ${{ steps.check_tag.outputs.tag_exists }}
        echo ${{ steps.check_tag.outputs.tag_exists }} == 'false'

    - name: Create tag
      if: steps.check_tag.outputs.tag_exists == 'false'
      id: create_tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.read_version.outputs.version }}
        tag_prefix: ""

    - name: Display Tag
      if: steps.create_tag.outputs.new_tag != ''
      run: |
        echo "Tag created: ${{ steps.create_tag.outputs.new_tag }}"
      # run: |
      #   VERSION=${{ steps.read_version.outputs.version }}
      #   git tag "$VERSION"
      #   git push origin "$VERSION"
      #   echo "$VERSION tag created."
